//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blood_donation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BloodEntities : DbContext
    {
        public BloodEntities()
            : base("name=BloodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBL_Contact> TBL_Contact { get; set; }
        public DbSet<TBL_Login> TBL_Login { get; set; }
        public DbSet<TBL_newLogin> TBL_newLogin { get; set; }
        public DbSet<TBL_Registration> TBL_Registration { get; set; }
    }
}
