//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blood_donation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Registration
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Profile { get; set; }
        public string Qualification { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public string DOB { get; set; }
        public string RegDate { get; set; }
    }
}
